about/urls.py
from django.urls import path

from . import views

app_name = 'about'
urlpatterns = [
    path('', views.about, name='about'),
]

demo_app/urls.py
from django.urls import path

from . import views

app_name = 'demo'
urlpatterns = [
    path('', views.welcome_page, name='welcome'),
]

demo_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', include('about.urls', namespace='about')),
    path('', include('demo_app.urls', namespace='demo')),
]

about/models.py
from django.db import models

# Create your models here.

demo_app/models.py
from django.db import models

# Create your models here.

about/views.py
from django.shortcuts import render


def about(request):
    context = {
        'title': 'About Us'
    }
    return render(request, 'about/about.html', context)

demo_app/views.py
from django.shortcuts import render


def welcome_page(request):
    context = {
        'title': 'Welcome!'
    }
    return render(request, 'demo_app/welcome.html', context)

templates/about/about.html
{% extends 'base.html' %}

{% block content %}
  <h1>You're looking at the awesome about page</h1>
{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
  <!-- Google Fonts -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
  <!-- Bootstrap core CSS -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.1/css/mdb.min.css" rel="stylesheet">
  <!-- Custom Styles -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <!-- Site Icon -->
  <link rel="icon" href="https://img.icons8.com/officel/16/000000/protection-mask.png">



  {% block link %}
  {% endblock link %}

  {% if title %}
    <title> {{ title }} </title>
  {% else %}
    <title>Demo Project</title>
  {% endif %}
</head>
<body>
  <!-- Nav Bar -->
  {% include 'partials/_navbar.html' %}
  
  <main role="main" class="container mb-4">
    <!-- Alerts -->
    {% include 'partials/_alerts.html' %}

    <!-- Page Content -->
    {% block content %} {% endblock content %}
  </main>

  <!-- Footer -->
  {% include 'partials/_footer.html' %}

  <!-- JQuery -->
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/js/bootstrap.min.js"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.1/js/mdb.min.js"></script>
  <script src="{% static 'js/main.js' %}"></script>
  <!-- Custom JS Scripts -->
  {% block script %}{% endblock script %}

</body>
</html>

templates/demo_app/welcome.html
{% extends 'base.html' %}

{% block content %}
  <h1>Welcome to the demo project</h1>
{% endblock content %}

templates/partials/_alerts.html
{% if messages %}
  {% for message in messages %}
    <div class="container message">
      <div class="alert alert-{{ message.tags }} alert-dismissable text-center" role="alert">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
        </button>
        <strong>
          {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
            Error:
          {% else %}
            {{ message.tags|title }}
          {% endif %}
        </strong>
        {{ message }}
      </div>
    </div>
  {% endfor %}
{% endif %}

templates/partials/_footer.html
<!-- Footer -->
<footer class="page-footer font-small fixed-bottom special-color-dark">

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="#"> Leo K</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

templates/partials/_navbar.html
<!--Navbar -->
<nav class="mb-1 navbar navbar-expand-lg navbar-dark orange lighten-1">
  <a class="navbar-brand" href="{% url 'demo:welcome' %}">Demo Project</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-555"
    aria-controls="navbarSupportedContent-555" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent-555">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item
        {% if '/' == request.path %}
          active
        {% endif %}
      ">
        <a class="nav-link" href="{% url 'demo:welcome' %}">HOME
          <span class="sr-only">(current)</span>
        </a>
      </li>
      <li class="nav-item
        {% if 'about' in request.path %}
          active
        {% endif %}
      ">
        <a class="nav-link" href="{% url 'about:about' %}">ABOUT
          <span class="sr-only">(current)</span>
        </a>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link p-0" href="#">
            ADMIN LOGIN
          </a>
        </li>
    </ul>
  </div>
</nav>
<!--/.Navbar -->